version: '3.7'
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS=127.0.0.1,localhost
#  proxy:
#    image: nginx
#    ports:
#      - 8000:8080
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
#    restart: unless-stopped
#    depends_on:
#      - app
