# Generated by Django 3.1.2 on 2020-10-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='make_name',
            new_name='car_make',
        ),
    ]
